package project

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
)

const (
	AgentGuideFileName    = "AGENTS.md"
	ProjectReadmeFileName = "README.md"
)

func DefaultProjectReadmeMarkdown() string {
	return `# SegmentStream Project

This repository is a SegmentStream project. SegmentStream projects are
code-driven: committed project files describe the measurement setup, and the
CLI regenerates local runtime files from that source of truth.

## Project Structure

` + "```text" + `
segmentstream.yml       project configuration and warehouse wiring
README.md               project documentation
AGENTS.md               instructions for LLM/code agents
.gitignore              should include .segmentstream/
.segmentstream/         generated dbt/Dagster/Docker runtime, disposable
` + "```" + `

Future project-owned folders such as ` + "`sources/`" + `, ` + "`destinations/`" + `, and
` + "`attribution_models/`" + ` should live outside ` + "`.segmentstream/`" + `.

## Source Of Truth

- ` + "`segmentstream.yml`" + ` is the committed project configuration.
- ` + "`warehouse.auth`" + ` is a named credential reference, not a secret value.
- Do not put credentials, tokens, private keys, or SQL in ` + "`segmentstream.yml`" + `.
- ` + "`requires.segmentstream`" + ` may be present, but the current CLI only parses it.

## Generated Runtime

- ` + "`.segmentstream/`" + ` is generated by the CLI and is listed in ` + "`.gitignore`" + `.
- Do not edit files inside ` + "`.segmentstream/`" + ` directly.
- The CLI may delete and recreate ` + "`.segmentstream/`" + ` at any time.
- Run ` + "`segmentstream prepare`" + ` after changing ` + "`segmentstream.yml`" + `.

## Commands

` + "```sh" + `
segmentstream init
segmentstream prepare
segmentstream run
` + "```" + `

` + "`segmentstream init`" + ` creates the initial project files if they are missing and
prepares the generated runtime.

` + "`segmentstream prepare`" + ` reads ` + "`segmentstream.yml`" + ` and recreates the disposable
project-local ` + "`.segmentstream/`" + ` runtime directory with Docker Compose, dbt, and
Dagster files.

` + "`segmentstream run`" + ` validates Docker, prepares ` + "`.segmentstream/`" + `, and starts
the local Dagster/dbt runtime at http://localhost:3000.
The first run can take a few minutes while Docker downloads and builds the
local environment; later runs should be faster.

## BigQuery Warehouse Configuration

SegmentStream config version 1 supports Google BigQuery as the warehouse.

Configure the warehouse in ` + "`segmentstream.yml`" + `:

` + "```yaml" + `
version: 1

warehouse:
  type: bigquery
  auth: default-bigquery
  project: your-gcp-project
  dataset: segmentstream
  location: US
` + "```" + `

### Fields

- ` + "`version`" + ` must be ` + "`1`" + `.
- ` + "`warehouse.type`" + ` must be ` + "`bigquery`" + `.
- ` + "`warehouse.auth`" + ` is a named credential reference. It is not a secret.
- ` + "`warehouse.project`" + ` is the Google Cloud project ID.
- ` + "`warehouse.dataset`" + ` is the BigQuery dataset for SegmentStream models.
- ` + "`warehouse.location`" + ` is optional and defaults to ` + "`US`" + `.
`
}

func DefaultAgentGuideMarkdown() string {
	return `# Agent Instructions

This repository is a SegmentStream project.

Before editing SegmentStream project files, read ` + "`README.md`" + ` in this directory.

## Rules

- Treat ` + "`segmentstream.yml`" + ` as the source of truth for project configuration.
- Do not edit files inside ` + "`.segmentstream/`" + `; it is generated and disposable.
- Run ` + "`segmentstream prepare`" + ` after changing ` + "`segmentstream.yml`" + `.
- Use ` + "`segmentstream run`" + ` to start the local generated runtime.
- Do not put secrets, credentials, private keys, tokens, or SQL in ` + "`segmentstream.yml`" + `.
- For BigQuery warehouse configuration, use the guidance in ` + "`README.md`" + `.
`
}

func EnsureProjectReadme(projectRoot string) (bool, error) {
	return ensureGuideFile(projectRoot, ProjectReadmeFileName, DefaultProjectReadmeMarkdown())
}

func EnsureAgentGuide(projectRoot string) (bool, error) {
	return ensureGuideFile(projectRoot, AgentGuideFileName, DefaultAgentGuideMarkdown())
}

func ensureGuideFile(projectRoot, name, content string) (bool, error) {
	path := filepath.Join(projectRoot, name)
	if _, err := os.Stat(path); err != nil {
		if errors.Is(err, os.ErrNotExist) {
			if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
				return false, fmt.Errorf("write %s: %w", name, err)
			}
			return true, nil
		}
		return false, fmt.Errorf("check %s: %w", name, err)
	}
	return false, nil
}
