FROM python:3.11-slim

ENV PIP_NO_CACHE_DIR=1

RUN pip install \
    "dbt-bigquery>=1.8,<1.9" \
    "dagster>=1.7,<1.8" \
    "dagster-dbt>=0.23,<0.24" \
    "dagster-webserver>=1.7,<1.8"

WORKDIR /workspace/.segmentstream

