name: __PACKAGE_NAME__
version: "0.1.0"
config-version: 2

model-paths:
  - models
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots

target-path: target
clean-targets:
  - target
  - dbt_packages

models:
  __PACKAGE_NAME__:
    staging:
      +materialized: view
    exports:
      +materialized: incremental
      +incremental_strategy: insert_overwrite
      +partition_by:
        field: event_date
        data_type: date
        granularity: day
