segmentstream:
  target: default
  outputs:
    default:
      type: bigquery
      method: oauth
      project: "{{ env_var('SEGMENTSTREAM_BQ_PROJECT') }}"
      dataset: "{{ env_var('SEGMENTSTREAM_BQ_DATASET') }}"
      location: "{{ env_var('SEGMENTSTREAM_BQ_LOCATION', 'US') }}"
      threads: 4
      priority: interactive
      retries: 1
