// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package dagster

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/Khan/genqlient/graphql"
)

type AssetKeyInput struct {
	Path []string `json:"path"`
}

// GetPath returns AssetKeyInput.Path, and is useful for accessing the field via an interface.
func (v *AssetKeyInput) GetPath() []string { return v.Path }

type ExecutionTag struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// GetKey returns ExecutionTag.Key, and is useful for accessing the field via an interface.
func (v *ExecutionTag) GetKey() string { return v.Key }

// GetValue returns ExecutionTag.Value, and is useful for accessing the field via an interface.
func (v *ExecutionTag) GetValue() string { return v.Value }

type LaunchBackfillParams struct {
	PartitionsByAssets []*PartitionsByAssetSelector `json:"partitionsByAssets"`
	Tags               []ExecutionTag               `json:"tags"`
	Title              *string                      `json:"title"`
	Description        *string                      `json:"description"`
}

// GetPartitionsByAssets returns LaunchBackfillParams.PartitionsByAssets, and is useful for accessing the field via an interface.
func (v *LaunchBackfillParams) GetPartitionsByAssets() []*PartitionsByAssetSelector {
	return v.PartitionsByAssets
}

// GetTags returns LaunchBackfillParams.Tags, and is useful for accessing the field via an interface.
func (v *LaunchBackfillParams) GetTags() []ExecutionTag { return v.Tags }

// GetTitle returns LaunchBackfillParams.Title, and is useful for accessing the field via an interface.
func (v *LaunchBackfillParams) GetTitle() *string { return v.Title }

// GetDescription returns LaunchBackfillParams.Description, and is useful for accessing the field via an interface.
func (v *LaunchBackfillParams) GetDescription() *string { return v.Description }

type PartitionRangeSelector struct {
	Start string `json:"start"`
	End   string `json:"end"`
}

// GetStart returns PartitionRangeSelector.Start, and is useful for accessing the field via an interface.
func (v *PartitionRangeSelector) GetStart() string { return v.Start }

// GetEnd returns PartitionRangeSelector.End, and is useful for accessing the field via an interface.
func (v *PartitionRangeSelector) GetEnd() string { return v.End }

type PartitionsByAssetSelector struct {
	AssetKey   AssetKeyInput       `json:"assetKey"`
	Partitions *PartitionsSelector `json:"partitions"`
}

// GetAssetKey returns PartitionsByAssetSelector.AssetKey, and is useful for accessing the field via an interface.
func (v *PartitionsByAssetSelector) GetAssetKey() AssetKeyInput { return v.AssetKey }

// GetPartitions returns PartitionsByAssetSelector.Partitions, and is useful for accessing the field via an interface.
func (v *PartitionsByAssetSelector) GetPartitions() *PartitionsSelector { return v.Partitions }

type PartitionsSelector struct {
	Range *PartitionRangeSelector `json:"range"`
}

// GetRange returns PartitionsSelector.Range, and is useful for accessing the field via an interface.
func (v *PartitionsSelector) GetRange() *PartitionRangeSelector { return v.Range }

// SegmentStreamAssetsAssetNodesAssetNode includes the requested fields of the GraphQL type AssetNode.
type SegmentStreamAssetsAssetNodesAssetNode struct {
	AssetKey         SegmentStreamAssetsAssetNodesAssetNodeAssetKey `json:"assetKey"`
	IsMaterializable bool                                           `json:"isMaterializable"`
	IsPartitioned    bool                                           `json:"isPartitioned"`
}

// GetAssetKey returns SegmentStreamAssetsAssetNodesAssetNode.AssetKey, and is useful for accessing the field via an interface.
func (v *SegmentStreamAssetsAssetNodesAssetNode) GetAssetKey() SegmentStreamAssetsAssetNodesAssetNodeAssetKey {
	return v.AssetKey
}

// GetIsMaterializable returns SegmentStreamAssetsAssetNodesAssetNode.IsMaterializable, and is useful for accessing the field via an interface.
func (v *SegmentStreamAssetsAssetNodesAssetNode) GetIsMaterializable() bool {
	return v.IsMaterializable
}

// GetIsPartitioned returns SegmentStreamAssetsAssetNodesAssetNode.IsPartitioned, and is useful for accessing the field via an interface.
func (v *SegmentStreamAssetsAssetNodesAssetNode) GetIsPartitioned() bool { return v.IsPartitioned }

// SegmentStreamAssetsAssetNodesAssetNodeAssetKey includes the requested fields of the GraphQL type AssetKey.
type SegmentStreamAssetsAssetNodesAssetNodeAssetKey struct {
	Path []string `json:"path"`
}

// GetPath returns SegmentStreamAssetsAssetNodesAssetNodeAssetKey.Path, and is useful for accessing the field via an interface.
func (v *SegmentStreamAssetsAssetNodesAssetNodeAssetKey) GetPath() []string { return v.Path }

// SegmentStreamAssetsResponse is returned by SegmentStreamAssets on success.
type SegmentStreamAssetsResponse struct {
	AssetNodes []SegmentStreamAssetsAssetNodesAssetNode `json:"assetNodes"`
}

// GetAssetNodes returns SegmentStreamAssetsResponse.AssetNodes, and is useful for accessing the field via an interface.
func (v *SegmentStreamAssetsResponse) GetAssetNodes() []SegmentStreamAssetsAssetNodesAssetNode {
	return v.AssetNodes
}

// SegmentStreamBackfillStatusPartitionBackfillOrError includes the requested fields of the GraphQL interface PartitionBackfillOrError.
//
// SegmentStreamBackfillStatusPartitionBackfillOrError is implemented by the following types:
// SegmentStreamBackfillStatusPartitionBackfillOrErrorBackfillNotFoundError
// SegmentStreamBackfillStatusPartitionBackfillOrErrorPartitionBackfill
// SegmentStreamBackfillStatusPartitionBackfillOrErrorPythonError
type SegmentStreamBackfillStatusPartitionBackfillOrError interface {
	implementsGraphQLInterfaceSegmentStreamBackfillStatusPartitionBackfillOrError()
	// GetTypename returns the receiver's concrete GraphQL type-name (see interface doc for possible values).
	GetTypename() *string
}

func (v *SegmentStreamBackfillStatusPartitionBackfillOrErrorBackfillNotFoundError) implementsGraphQLInterfaceSegmentStreamBackfillStatusPartitionBackfillOrError() {
}
func (v *SegmentStreamBackfillStatusPartitionBackfillOrErrorPartitionBackfill) implementsGraphQLInterfaceSegmentStreamBackfillStatusPartitionBackfillOrError() {
}
func (v *SegmentStreamBackfillStatusPartitionBackfillOrErrorPythonError) implementsGraphQLInterfaceSegmentStreamBackfillStatusPartitionBackfillOrError() {
}

func __unmarshalSegmentStreamBackfillStatusPartitionBackfillOrError(b []byte, v *SegmentStreamBackfillStatusPartitionBackfillOrError) error {
	if string(b) == "null" {
		return nil
	}

	var tn struct {
		TypeName string `json:"__typename"`
	}
	err := json.Unmarshal(b, &tn)
	if err != nil {
		return err
	}

	switch tn.TypeName {
	case "BackfillNotFoundError":
		*v = new(SegmentStreamBackfillStatusPartitionBackfillOrErrorBackfillNotFoundError)
		return json.Unmarshal(b, *v)
	case "PartitionBackfill":
		*v = new(SegmentStreamBackfillStatusPartitionBackfillOrErrorPartitionBackfill)
		return json.Unmarshal(b, *v)
	case "PythonError":
		*v = new(SegmentStreamBackfillStatusPartitionBackfillOrErrorPythonError)
		return json.Unmarshal(b, *v)
	case "":
		return fmt.Errorf(
			"response was missing PartitionBackfillOrError.__typename")
	default:
		return fmt.Errorf(
			`unexpected concrete type for SegmentStreamBackfillStatusPartitionBackfillOrError: "%v"`, tn.TypeName)
	}
}

func __marshalSegmentStreamBackfillStatusPartitionBackfillOrError(v *SegmentStreamBackfillStatusPartitionBackfillOrError) ([]byte, error) {

	var typename string
	switch v := (*v).(type) {
	case *SegmentStreamBackfillStatusPartitionBackfillOrErrorBackfillNotFoundError:
		typename = "BackfillNotFoundError"

		result := struct {
			TypeName string `json:"__typename"`
			*SegmentStreamBackfillStatusPartitionBackfillOrErrorBackfillNotFoundError
		}{typename, v}
		return json.Marshal(result)
	case *SegmentStreamBackfillStatusPartitionBackfillOrErrorPartitionBackfill:
		typename = "PartitionBackfill"

		result := struct {
			TypeName string `json:"__typename"`
			*SegmentStreamBackfillStatusPartitionBackfillOrErrorPartitionBackfill
		}{typename, v}
		return json.Marshal(result)
	case *SegmentStreamBackfillStatusPartitionBackfillOrErrorPythonError:
		typename = "PythonError"

		result := struct {
			TypeName string `json:"__typename"`
			*SegmentStreamBackfillStatusPartitionBackfillOrErrorPythonError
		}{typename, v}
		return json.Marshal(result)
	case nil:
		return []byte("null"), nil
	default:
		return nil, fmt.Errorf(
			`unexpected concrete type for SegmentStreamBackfillStatusPartitionBackfillOrError: "%T"`, v)
	}
}

// SegmentStreamBackfillStatusPartitionBackfillOrErrorBackfillNotFoundError includes the requested fields of the GraphQL type BackfillNotFoundError.
type SegmentStreamBackfillStatusPartitionBackfillOrErrorBackfillNotFoundError struct {
	Typename *string `json:"__typename"`
	Message  string  `json:"message"`
}

// GetTypename returns SegmentStreamBackfillStatusPartitionBackfillOrErrorBackfillNotFoundError.Typename, and is useful for accessing the field via an interface.
func (v *SegmentStreamBackfillStatusPartitionBackfillOrErrorBackfillNotFoundError) GetTypename() *string {
	return v.Typename
}

// GetMessage returns SegmentStreamBackfillStatusPartitionBackfillOrErrorBackfillNotFoundError.Message, and is useful for accessing the field via an interface.
func (v *SegmentStreamBackfillStatusPartitionBackfillOrErrorBackfillNotFoundError) GetMessage() string {
	return v.Message
}

// SegmentStreamBackfillStatusPartitionBackfillOrErrorPartitionBackfill includes the requested fields of the GraphQL type PartitionBackfill.
type SegmentStreamBackfillStatusPartitionBackfillOrErrorPartitionBackfill struct {
	Typename *string                                                                               `json:"__typename"`
	Status   string                                                                                `json:"status"`
	Error    *SegmentStreamBackfillStatusPartitionBackfillOrErrorPartitionBackfillErrorPythonError `json:"error"`
}

// GetTypename returns SegmentStreamBackfillStatusPartitionBackfillOrErrorPartitionBackfill.Typename, and is useful for accessing the field via an interface.
func (v *SegmentStreamBackfillStatusPartitionBackfillOrErrorPartitionBackfill) GetTypename() *string {
	return v.Typename
}

// GetStatus returns SegmentStreamBackfillStatusPartitionBackfillOrErrorPartitionBackfill.Status, and is useful for accessing the field via an interface.
func (v *SegmentStreamBackfillStatusPartitionBackfillOrErrorPartitionBackfill) GetStatus() string {
	return v.Status
}

// GetError returns SegmentStreamBackfillStatusPartitionBackfillOrErrorPartitionBackfill.Error, and is useful for accessing the field via an interface.
func (v *SegmentStreamBackfillStatusPartitionBackfillOrErrorPartitionBackfill) GetError() *SegmentStreamBackfillStatusPartitionBackfillOrErrorPartitionBackfillErrorPythonError {
	return v.Error
}

// SegmentStreamBackfillStatusPartitionBackfillOrErrorPartitionBackfillErrorPythonError includes the requested fields of the GraphQL type PythonError.
type SegmentStreamBackfillStatusPartitionBackfillOrErrorPartitionBackfillErrorPythonError struct {
	Message string `json:"message"`
}

// GetMessage returns SegmentStreamBackfillStatusPartitionBackfillOrErrorPartitionBackfillErrorPythonError.Message, and is useful for accessing the field via an interface.
func (v *SegmentStreamBackfillStatusPartitionBackfillOrErrorPartitionBackfillErrorPythonError) GetMessage() string {
	return v.Message
}

// SegmentStreamBackfillStatusPartitionBackfillOrErrorPythonError includes the requested fields of the GraphQL type PythonError.
type SegmentStreamBackfillStatusPartitionBackfillOrErrorPythonError struct {
	Typename *string `json:"__typename"`
	Message  string  `json:"message"`
}

// GetTypename returns SegmentStreamBackfillStatusPartitionBackfillOrErrorPythonError.Typename, and is useful for accessing the field via an interface.
func (v *SegmentStreamBackfillStatusPartitionBackfillOrErrorPythonError) GetTypename() *string {
	return v.Typename
}

// GetMessage returns SegmentStreamBackfillStatusPartitionBackfillOrErrorPythonError.Message, and is useful for accessing the field via an interface.
func (v *SegmentStreamBackfillStatusPartitionBackfillOrErrorPythonError) GetMessage() string {
	return v.Message
}

// SegmentStreamBackfillStatusResponse is returned by SegmentStreamBackfillStatus on success.
type SegmentStreamBackfillStatusResponse struct {
	PartitionBackfillOrError SegmentStreamBackfillStatusPartitionBackfillOrError `json:"-"`
}

// GetPartitionBackfillOrError returns SegmentStreamBackfillStatusResponse.PartitionBackfillOrError, and is useful for accessing the field via an interface.
func (v *SegmentStreamBackfillStatusResponse) GetPartitionBackfillOrError() SegmentStreamBackfillStatusPartitionBackfillOrError {
	return v.PartitionBackfillOrError
}

func (v *SegmentStreamBackfillStatusResponse) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*SegmentStreamBackfillStatusResponse
		PartitionBackfillOrError json.RawMessage `json:"partitionBackfillOrError"`
		graphql.NoUnmarshalJSON
	}
	firstPass.SegmentStreamBackfillStatusResponse = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.PartitionBackfillOrError
		src := firstPass.PartitionBackfillOrError
		if len(src) != 0 && string(src) != "null" {
			err = __unmarshalSegmentStreamBackfillStatusPartitionBackfillOrError(
				src, dst)
			if err != nil {
				return fmt.Errorf(
					"unable to unmarshal SegmentStreamBackfillStatusResponse.PartitionBackfillOrError: %w", err)
			}
		}
	}
	return nil
}

type __premarshalSegmentStreamBackfillStatusResponse struct {
	PartitionBackfillOrError json.RawMessage `json:"partitionBackfillOrError"`
}

func (v *SegmentStreamBackfillStatusResponse) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *SegmentStreamBackfillStatusResponse) __premarshalJSON() (*__premarshalSegmentStreamBackfillStatusResponse, error) {
	var retval __premarshalSegmentStreamBackfillStatusResponse

	{

		dst := &retval.PartitionBackfillOrError
		src := v.PartitionBackfillOrError
		var err error
		*dst, err = __marshalSegmentStreamBackfillStatusPartitionBackfillOrError(
			&src)
		if err != nil {
			return nil, fmt.Errorf(
				"unable to marshal SegmentStreamBackfillStatusResponse.PartitionBackfillOrError: %w", err)
		}
	}
	return &retval, nil
}

// SegmentStreamLaunchBackfillLaunchPartitionBackfillConflictingExecutionParamsError includes the requested fields of the GraphQL type ConflictingExecutionParamsError.
type SegmentStreamLaunchBackfillLaunchPartitionBackfillConflictingExecutionParamsError struct {
	Typename *string `json:"__typename"`
	Message  string  `json:"message"`
}

// GetTypename returns SegmentStreamLaunchBackfillLaunchPartitionBackfillConflictingExecutionParamsError.Typename, and is useful for accessing the field via an interface.
func (v *SegmentStreamLaunchBackfillLaunchPartitionBackfillConflictingExecutionParamsError) GetTypename() *string {
	return v.Typename
}

// GetMessage returns SegmentStreamLaunchBackfillLaunchPartitionBackfillConflictingExecutionParamsError.Message, and is useful for accessing the field via an interface.
func (v *SegmentStreamLaunchBackfillLaunchPartitionBackfillConflictingExecutionParamsError) GetMessage() string {
	return v.Message
}

// SegmentStreamLaunchBackfillLaunchPartitionBackfillInvalidOutputError includes the requested fields of the GraphQL type InvalidOutputError.
type SegmentStreamLaunchBackfillLaunchPartitionBackfillInvalidOutputError struct {
	Typename *string `json:"__typename"`
}

// GetTypename returns SegmentStreamLaunchBackfillLaunchPartitionBackfillInvalidOutputError.Typename, and is useful for accessing the field via an interface.
func (v *SegmentStreamLaunchBackfillLaunchPartitionBackfillInvalidOutputError) GetTypename() *string {
	return v.Typename
}

// SegmentStreamLaunchBackfillLaunchPartitionBackfillInvalidStepError includes the requested fields of the GraphQL type InvalidStepError.
type SegmentStreamLaunchBackfillLaunchPartitionBackfillInvalidStepError struct {
	Typename *string `json:"__typename"`
}

// GetTypename returns SegmentStreamLaunchBackfillLaunchPartitionBackfillInvalidStepError.Typename, and is useful for accessing the field via an interface.
func (v *SegmentStreamLaunchBackfillLaunchPartitionBackfillInvalidStepError) GetTypename() *string {
	return v.Typename
}

// SegmentStreamLaunchBackfillLaunchPartitionBackfillInvalidSubsetError includes the requested fields of the GraphQL type InvalidSubsetError.
type SegmentStreamLaunchBackfillLaunchPartitionBackfillInvalidSubsetError struct {
	Typename *string `json:"__typename"`
	Message  string  `json:"message"`
}

// GetTypename returns SegmentStreamLaunchBackfillLaunchPartitionBackfillInvalidSubsetError.Typename, and is useful for accessing the field via an interface.
func (v *SegmentStreamLaunchBackfillLaunchPartitionBackfillInvalidSubsetError) GetTypename() *string {
	return v.Typename
}

// GetMessage returns SegmentStreamLaunchBackfillLaunchPartitionBackfillInvalidSubsetError.Message, and is useful for accessing the field via an interface.
func (v *SegmentStreamLaunchBackfillLaunchPartitionBackfillInvalidSubsetError) GetMessage() string {
	return v.Message
}

// SegmentStreamLaunchBackfillLaunchPartitionBackfillLaunchBackfillResult includes the requested fields of the GraphQL interface LaunchBackfillResult.
//
// SegmentStreamLaunchBackfillLaunchPartitionBackfillLaunchBackfillResult is implemented by the following types:
// SegmentStreamLaunchBackfillLaunchPartitionBackfillConflictingExecutionParamsError
// SegmentStreamLaunchBackfillLaunchPartitionBackfillInvalidOutputError
// SegmentStreamLaunchBackfillLaunchPartitionBackfillInvalidStepError
// SegmentStreamLaunchBackfillLaunchPartitionBackfillInvalidSubsetError
// SegmentStreamLaunchBackfillLaunchPartitionBackfillLaunchBackfillSuccess
// SegmentStreamLaunchBackfillLaunchPartitionBackfillNoModeProvidedError
// SegmentStreamLaunchBackfillLaunchPartitionBackfillPartitionKeysNotFoundError
// SegmentStreamLaunchBackfillLaunchPartitionBackfillPartitionSetNotFoundError
// SegmentStreamLaunchBackfillLaunchPartitionBackfillPipelineNotFoundError
// SegmentStreamLaunchBackfillLaunchPartitionBackfillPresetNotFoundError
// SegmentStreamLaunchBackfillLaunchPartitionBackfillPythonError
// SegmentStreamLaunchBackfillLaunchPartitionBackfillRunConfigValidationInvalid
// SegmentStreamLaunchBackfillLaunchPartitionBackfillRunConflict
// SegmentStreamLaunchBackfillLaunchPartitionBackfillUnauthorizedError
type SegmentStreamLaunchBackfillLaunchPartitionBackfillLaunchBackfillResult interface {
	implementsGraphQLInterfaceSegmentStreamLaunchBackfillLaunchPartitionBackfillLaunchBackfillResult()
	// GetTypename returns the receiver's concrete GraphQL type-name (see interface doc for possible values).
	GetTypename() *string
}

func (v *SegmentStreamLaunchBackfillLaunchPartitionBackfillConflictingExecutionParamsError) implementsGraphQLInterfaceSegmentStreamLaunchBackfillLaunchPartitionBackfillLaunchBackfillResult() {
}
func (v *SegmentStreamLaunchBackfillLaunchPartitionBackfillInvalidOutputError) implementsGraphQLInterfaceSegmentStreamLaunchBackfillLaunchPartitionBackfillLaunchBackfillResult() {
}
func (v *SegmentStreamLaunchBackfillLaunchPartitionBackfillInvalidStepError) implementsGraphQLInterfaceSegmentStreamLaunchBackfillLaunchPartitionBackfillLaunchBackfillResult() {
}
func (v *SegmentStreamLaunchBackfillLaunchPartitionBackfillInvalidSubsetError) implementsGraphQLInterfaceSegmentStreamLaunchBackfillLaunchPartitionBackfillLaunchBackfillResult() {
}
func (v *SegmentStreamLaunchBackfillLaunchPartitionBackfillLaunchBackfillSuccess) implementsGraphQLInterfaceSegmentStreamLaunchBackfillLaunchPartitionBackfillLaunchBackfillResult() {
}
func (v *SegmentStreamLaunchBackfillLaunchPartitionBackfillNoModeProvidedError) implementsGraphQLInterfaceSegmentStreamLaunchBackfillLaunchPartitionBackfillLaunchBackfillResult() {
}
func (v *SegmentStreamLaunchBackfillLaunchPartitionBackfillPartitionKeysNotFoundError) implementsGraphQLInterfaceSegmentStreamLaunchBackfillLaunchPartitionBackfillLaunchBackfillResult() {
}
func (v *SegmentStreamLaunchBackfillLaunchPartitionBackfillPartitionSetNotFoundError) implementsGraphQLInterfaceSegmentStreamLaunchBackfillLaunchPartitionBackfillLaunchBackfillResult() {
}
func (v *SegmentStreamLaunchBackfillLaunchPartitionBackfillPipelineNotFoundError) implementsGraphQLInterfaceSegmentStreamLaunchBackfillLaunchPartitionBackfillLaunchBackfillResult() {
}
func (v *SegmentStreamLaunchBackfillLaunchPartitionBackfillPresetNotFoundError) implementsGraphQLInterfaceSegmentStreamLaunchBackfillLaunchPartitionBackfillLaunchBackfillResult() {
}
func (v *SegmentStreamLaunchBackfillLaunchPartitionBackfillPythonError) implementsGraphQLInterfaceSegmentStreamLaunchBackfillLaunchPartitionBackfillLaunchBackfillResult() {
}
func (v *SegmentStreamLaunchBackfillLaunchPartitionBackfillRunConfigValidationInvalid) implementsGraphQLInterfaceSegmentStreamLaunchBackfillLaunchPartitionBackfillLaunchBackfillResult() {
}
func (v *SegmentStreamLaunchBackfillLaunchPartitionBackfillRunConflict) implementsGraphQLInterfaceSegmentStreamLaunchBackfillLaunchPartitionBackfillLaunchBackfillResult() {
}
func (v *SegmentStreamLaunchBackfillLaunchPartitionBackfillUnauthorizedError) implementsGraphQLInterfaceSegmentStreamLaunchBackfillLaunchPartitionBackfillLaunchBackfillResult() {
}

func __unmarshalSegmentStreamLaunchBackfillLaunchPartitionBackfillLaunchBackfillResult(b []byte, v *SegmentStreamLaunchBackfillLaunchPartitionBackfillLaunchBackfillResult) error {
	if string(b) == "null" {
		return nil
	}

	var tn struct {
		TypeName string `json:"__typename"`
	}
	err := json.Unmarshal(b, &tn)
	if err != nil {
		return err
	}

	switch tn.TypeName {
	case "ConflictingExecutionParamsError":
		*v = new(SegmentStreamLaunchBackfillLaunchPartitionBackfillConflictingExecutionParamsError)
		return json.Unmarshal(b, *v)
	case "InvalidOutputError":
		*v = new(SegmentStreamLaunchBackfillLaunchPartitionBackfillInvalidOutputError)
		return json.Unmarshal(b, *v)
	case "InvalidStepError":
		*v = new(SegmentStreamLaunchBackfillLaunchPartitionBackfillInvalidStepError)
		return json.Unmarshal(b, *v)
	case "InvalidSubsetError":
		*v = new(SegmentStreamLaunchBackfillLaunchPartitionBackfillInvalidSubsetError)
		return json.Unmarshal(b, *v)
	case "LaunchBackfillSuccess":
		*v = new(SegmentStreamLaunchBackfillLaunchPartitionBackfillLaunchBackfillSuccess)
		return json.Unmarshal(b, *v)
	case "NoModeProvidedError":
		*v = new(SegmentStreamLaunchBackfillLaunchPartitionBackfillNoModeProvidedError)
		return json.Unmarshal(b, *v)
	case "PartitionKeysNotFoundError":
		*v = new(SegmentStreamLaunchBackfillLaunchPartitionBackfillPartitionKeysNotFoundError)
		return json.Unmarshal(b, *v)
	case "PartitionSetNotFoundError":
		*v = new(SegmentStreamLaunchBackfillLaunchPartitionBackfillPartitionSetNotFoundError)
		return json.Unmarshal(b, *v)
	case "PipelineNotFoundError":
		*v = new(SegmentStreamLaunchBackfillLaunchPartitionBackfillPipelineNotFoundError)
		return json.Unmarshal(b, *v)
	case "PresetNotFoundError":
		*v = new(SegmentStreamLaunchBackfillLaunchPartitionBackfillPresetNotFoundError)
		return json.Unmarshal(b, *v)
	case "PythonError":
		*v = new(SegmentStreamLaunchBackfillLaunchPartitionBackfillPythonError)
		return json.Unmarshal(b, *v)
	case "RunConfigValidationInvalid":
		*v = new(SegmentStreamLaunchBackfillLaunchPartitionBackfillRunConfigValidationInvalid)
		return json.Unmarshal(b, *v)
	case "RunConflict":
		*v = new(SegmentStreamLaunchBackfillLaunchPartitionBackfillRunConflict)
		return json.Unmarshal(b, *v)
	case "UnauthorizedError":
		*v = new(SegmentStreamLaunchBackfillLaunchPartitionBackfillUnauthorizedError)
		return json.Unmarshal(b, *v)
	case "":
		return fmt.Errorf(
			"response was missing LaunchBackfillResult.__typename")
	default:
		return fmt.Errorf(
			`unexpected concrete type for SegmentStreamLaunchBackfillLaunchPartitionBackfillLaunchBackfillResult: "%v"`, tn.TypeName)
	}
}

func __marshalSegmentStreamLaunchBackfillLaunchPartitionBackfillLaunchBackfillResult(v *SegmentStreamLaunchBackfillLaunchPartitionBackfillLaunchBackfillResult) ([]byte, error) {

	var typename string
	switch v := (*v).(type) {
	case *SegmentStreamLaunchBackfillLaunchPartitionBackfillConflictingExecutionParamsError:
		typename = "ConflictingExecutionParamsError"

		result := struct {
			TypeName string `json:"__typename"`
			*SegmentStreamLaunchBackfillLaunchPartitionBackfillConflictingExecutionParamsError
		}{typename, v}
		return json.Marshal(result)
	case *SegmentStreamLaunchBackfillLaunchPartitionBackfillInvalidOutputError:
		typename = "InvalidOutputError"

		result := struct {
			TypeName string `json:"__typename"`
			*SegmentStreamLaunchBackfillLaunchPartitionBackfillInvalidOutputError
		}{typename, v}
		return json.Marshal(result)
	case *SegmentStreamLaunchBackfillLaunchPartitionBackfillInvalidStepError:
		typename = "InvalidStepError"

		result := struct {
			TypeName string `json:"__typename"`
			*SegmentStreamLaunchBackfillLaunchPartitionBackfillInvalidStepError
		}{typename, v}
		return json.Marshal(result)
	case *SegmentStreamLaunchBackfillLaunchPartitionBackfillInvalidSubsetError:
		typename = "InvalidSubsetError"

		result := struct {
			TypeName string `json:"__typename"`
			*SegmentStreamLaunchBackfillLaunchPartitionBackfillInvalidSubsetError
		}{typename, v}
		return json.Marshal(result)
	case *SegmentStreamLaunchBackfillLaunchPartitionBackfillLaunchBackfillSuccess:
		typename = "LaunchBackfillSuccess"

		result := struct {
			TypeName string `json:"__typename"`
			*SegmentStreamLaunchBackfillLaunchPartitionBackfillLaunchBackfillSuccess
		}{typename, v}
		return json.Marshal(result)
	case *SegmentStreamLaunchBackfillLaunchPartitionBackfillNoModeProvidedError:
		typename = "NoModeProvidedError"

		result := struct {
			TypeName string `json:"__typename"`
			*SegmentStreamLaunchBackfillLaunchPartitionBackfillNoModeProvidedError
		}{typename, v}
		return json.Marshal(result)
	case *SegmentStreamLaunchBackfillLaunchPartitionBackfillPartitionKeysNotFoundError:
		typename = "PartitionKeysNotFoundError"

		result := struct {
			TypeName string `json:"__typename"`
			*SegmentStreamLaunchBackfillLaunchPartitionBackfillPartitionKeysNotFoundError
		}{typename, v}
		return json.Marshal(result)
	case *SegmentStreamLaunchBackfillLaunchPartitionBackfillPartitionSetNotFoundError:
		typename = "PartitionSetNotFoundError"

		result := struct {
			TypeName string `json:"__typename"`
			*SegmentStreamLaunchBackfillLaunchPartitionBackfillPartitionSetNotFoundError
		}{typename, v}
		return json.Marshal(result)
	case *SegmentStreamLaunchBackfillLaunchPartitionBackfillPipelineNotFoundError:
		typename = "PipelineNotFoundError"

		result := struct {
			TypeName string `json:"__typename"`
			*SegmentStreamLaunchBackfillLaunchPartitionBackfillPipelineNotFoundError
		}{typename, v}
		return json.Marshal(result)
	case *SegmentStreamLaunchBackfillLaunchPartitionBackfillPresetNotFoundError:
		typename = "PresetNotFoundError"

		result := struct {
			TypeName string `json:"__typename"`
			*SegmentStreamLaunchBackfillLaunchPartitionBackfillPresetNotFoundError
		}{typename, v}
		return json.Marshal(result)
	case *SegmentStreamLaunchBackfillLaunchPartitionBackfillPythonError:
		typename = "PythonError"

		result := struct {
			TypeName string `json:"__typename"`
			*SegmentStreamLaunchBackfillLaunchPartitionBackfillPythonError
		}{typename, v}
		return json.Marshal(result)
	case *SegmentStreamLaunchBackfillLaunchPartitionBackfillRunConfigValidationInvalid:
		typename = "RunConfigValidationInvalid"

		result := struct {
			TypeName string `json:"__typename"`
			*SegmentStreamLaunchBackfillLaunchPartitionBackfillRunConfigValidationInvalid
		}{typename, v}
		return json.Marshal(result)
	case *SegmentStreamLaunchBackfillLaunchPartitionBackfillRunConflict:
		typename = "RunConflict"

		result := struct {
			TypeName string `json:"__typename"`
			*SegmentStreamLaunchBackfillLaunchPartitionBackfillRunConflict
		}{typename, v}
		return json.Marshal(result)
	case *SegmentStreamLaunchBackfillLaunchPartitionBackfillUnauthorizedError:
		typename = "UnauthorizedError"

		result := struct {
			TypeName string `json:"__typename"`
			*SegmentStreamLaunchBackfillLaunchPartitionBackfillUnauthorizedError
		}{typename, v}
		return json.Marshal(result)
	case nil:
		return []byte("null"), nil
	default:
		return nil, fmt.Errorf(
			`unexpected concrete type for SegmentStreamLaunchBackfillLaunchPartitionBackfillLaunchBackfillResult: "%T"`, v)
	}
}

// SegmentStreamLaunchBackfillLaunchPartitionBackfillLaunchBackfillSuccess includes the requested fields of the GraphQL type LaunchBackfillSuccess.
type SegmentStreamLaunchBackfillLaunchPartitionBackfillLaunchBackfillSuccess struct {
	Typename   *string `json:"__typename"`
	BackfillId string  `json:"backfillId"`
}

// GetTypename returns SegmentStreamLaunchBackfillLaunchPartitionBackfillLaunchBackfillSuccess.Typename, and is useful for accessing the field via an interface.
func (v *SegmentStreamLaunchBackfillLaunchPartitionBackfillLaunchBackfillSuccess) GetTypename() *string {
	return v.Typename
}

// GetBackfillId returns SegmentStreamLaunchBackfillLaunchPartitionBackfillLaunchBackfillSuccess.BackfillId, and is useful for accessing the field via an interface.
func (v *SegmentStreamLaunchBackfillLaunchPartitionBackfillLaunchBackfillSuccess) GetBackfillId() string {
	return v.BackfillId
}

// SegmentStreamLaunchBackfillLaunchPartitionBackfillNoModeProvidedError includes the requested fields of the GraphQL type NoModeProvidedError.
type SegmentStreamLaunchBackfillLaunchPartitionBackfillNoModeProvidedError struct {
	Typename *string `json:"__typename"`
	Message  string  `json:"message"`
}

// GetTypename returns SegmentStreamLaunchBackfillLaunchPartitionBackfillNoModeProvidedError.Typename, and is useful for accessing the field via an interface.
func (v *SegmentStreamLaunchBackfillLaunchPartitionBackfillNoModeProvidedError) GetTypename() *string {
	return v.Typename
}

// GetMessage returns SegmentStreamLaunchBackfillLaunchPartitionBackfillNoModeProvidedError.Message, and is useful for accessing the field via an interface.
func (v *SegmentStreamLaunchBackfillLaunchPartitionBackfillNoModeProvidedError) GetMessage() string {
	return v.Message
}

// SegmentStreamLaunchBackfillLaunchPartitionBackfillPartitionKeysNotFoundError includes the requested fields of the GraphQL type PartitionKeysNotFoundError.
type SegmentStreamLaunchBackfillLaunchPartitionBackfillPartitionKeysNotFoundError struct {
	Typename *string `json:"__typename"`
	Message  string  `json:"message"`
}

// GetTypename returns SegmentStreamLaunchBackfillLaunchPartitionBackfillPartitionKeysNotFoundError.Typename, and is useful for accessing the field via an interface.
func (v *SegmentStreamLaunchBackfillLaunchPartitionBackfillPartitionKeysNotFoundError) GetTypename() *string {
	return v.Typename
}

// GetMessage returns SegmentStreamLaunchBackfillLaunchPartitionBackfillPartitionKeysNotFoundError.Message, and is useful for accessing the field via an interface.
func (v *SegmentStreamLaunchBackfillLaunchPartitionBackfillPartitionKeysNotFoundError) GetMessage() string {
	return v.Message
}

// SegmentStreamLaunchBackfillLaunchPartitionBackfillPartitionSetNotFoundError includes the requested fields of the GraphQL type PartitionSetNotFoundError.
type SegmentStreamLaunchBackfillLaunchPartitionBackfillPartitionSetNotFoundError struct {
	Typename *string `json:"__typename"`
	Message  string  `json:"message"`
}

// GetTypename returns SegmentStreamLaunchBackfillLaunchPartitionBackfillPartitionSetNotFoundError.Typename, and is useful for accessing the field via an interface.
func (v *SegmentStreamLaunchBackfillLaunchPartitionBackfillPartitionSetNotFoundError) GetTypename() *string {
	return v.Typename
}

// GetMessage returns SegmentStreamLaunchBackfillLaunchPartitionBackfillPartitionSetNotFoundError.Message, and is useful for accessing the field via an interface.
func (v *SegmentStreamLaunchBackfillLaunchPartitionBackfillPartitionSetNotFoundError) GetMessage() string {
	return v.Message
}

// SegmentStreamLaunchBackfillLaunchPartitionBackfillPipelineNotFoundError includes the requested fields of the GraphQL type PipelineNotFoundError.
type SegmentStreamLaunchBackfillLaunchPartitionBackfillPipelineNotFoundError struct {
	Typename *string `json:"__typename"`
	Message  string  `json:"message"`
}

// GetTypename returns SegmentStreamLaunchBackfillLaunchPartitionBackfillPipelineNotFoundError.Typename, and is useful for accessing the field via an interface.
func (v *SegmentStreamLaunchBackfillLaunchPartitionBackfillPipelineNotFoundError) GetTypename() *string {
	return v.Typename
}

// GetMessage returns SegmentStreamLaunchBackfillLaunchPartitionBackfillPipelineNotFoundError.Message, and is useful for accessing the field via an interface.
func (v *SegmentStreamLaunchBackfillLaunchPartitionBackfillPipelineNotFoundError) GetMessage() string {
	return v.Message
}

// SegmentStreamLaunchBackfillLaunchPartitionBackfillPresetNotFoundError includes the requested fields of the GraphQL type PresetNotFoundError.
type SegmentStreamLaunchBackfillLaunchPartitionBackfillPresetNotFoundError struct {
	Typename *string `json:"__typename"`
	Message  string  `json:"message"`
}

// GetTypename returns SegmentStreamLaunchBackfillLaunchPartitionBackfillPresetNotFoundError.Typename, and is useful for accessing the field via an interface.
func (v *SegmentStreamLaunchBackfillLaunchPartitionBackfillPresetNotFoundError) GetTypename() *string {
	return v.Typename
}

// GetMessage returns SegmentStreamLaunchBackfillLaunchPartitionBackfillPresetNotFoundError.Message, and is useful for accessing the field via an interface.
func (v *SegmentStreamLaunchBackfillLaunchPartitionBackfillPresetNotFoundError) GetMessage() string {
	return v.Message
}

// SegmentStreamLaunchBackfillLaunchPartitionBackfillPythonError includes the requested fields of the GraphQL type PythonError.
type SegmentStreamLaunchBackfillLaunchPartitionBackfillPythonError struct {
	Typename *string `json:"__typename"`
	Message  string  `json:"message"`
}

// GetTypename returns SegmentStreamLaunchBackfillLaunchPartitionBackfillPythonError.Typename, and is useful for accessing the field via an interface.
func (v *SegmentStreamLaunchBackfillLaunchPartitionBackfillPythonError) GetTypename() *string {
	return v.Typename
}

// GetMessage returns SegmentStreamLaunchBackfillLaunchPartitionBackfillPythonError.Message, and is useful for accessing the field via an interface.
func (v *SegmentStreamLaunchBackfillLaunchPartitionBackfillPythonError) GetMessage() string {
	return v.Message
}

// SegmentStreamLaunchBackfillLaunchPartitionBackfillRunConfigValidationInvalid includes the requested fields of the GraphQL type RunConfigValidationInvalid.
type SegmentStreamLaunchBackfillLaunchPartitionBackfillRunConfigValidationInvalid struct {
	Typename *string `json:"__typename"`
	Message  string  `json:"message"`
}

// GetTypename returns SegmentStreamLaunchBackfillLaunchPartitionBackfillRunConfigValidationInvalid.Typename, and is useful for accessing the field via an interface.
func (v *SegmentStreamLaunchBackfillLaunchPartitionBackfillRunConfigValidationInvalid) GetTypename() *string {
	return v.Typename
}

// GetMessage returns SegmentStreamLaunchBackfillLaunchPartitionBackfillRunConfigValidationInvalid.Message, and is useful for accessing the field via an interface.
func (v *SegmentStreamLaunchBackfillLaunchPartitionBackfillRunConfigValidationInvalid) GetMessage() string {
	return v.Message
}

// SegmentStreamLaunchBackfillLaunchPartitionBackfillRunConflict includes the requested fields of the GraphQL type RunConflict.
type SegmentStreamLaunchBackfillLaunchPartitionBackfillRunConflict struct {
	Typename *string `json:"__typename"`
	Message  string  `json:"message"`
}

// GetTypename returns SegmentStreamLaunchBackfillLaunchPartitionBackfillRunConflict.Typename, and is useful for accessing the field via an interface.
func (v *SegmentStreamLaunchBackfillLaunchPartitionBackfillRunConflict) GetTypename() *string {
	return v.Typename
}

// GetMessage returns SegmentStreamLaunchBackfillLaunchPartitionBackfillRunConflict.Message, and is useful for accessing the field via an interface.
func (v *SegmentStreamLaunchBackfillLaunchPartitionBackfillRunConflict) GetMessage() string {
	return v.Message
}

// SegmentStreamLaunchBackfillLaunchPartitionBackfillUnauthorizedError includes the requested fields of the GraphQL type UnauthorizedError.
type SegmentStreamLaunchBackfillLaunchPartitionBackfillUnauthorizedError struct {
	Typename *string `json:"__typename"`
	Message  string  `json:"message"`
}

// GetTypename returns SegmentStreamLaunchBackfillLaunchPartitionBackfillUnauthorizedError.Typename, and is useful for accessing the field via an interface.
func (v *SegmentStreamLaunchBackfillLaunchPartitionBackfillUnauthorizedError) GetTypename() *string {
	return v.Typename
}

// GetMessage returns SegmentStreamLaunchBackfillLaunchPartitionBackfillUnauthorizedError.Message, and is useful for accessing the field via an interface.
func (v *SegmentStreamLaunchBackfillLaunchPartitionBackfillUnauthorizedError) GetMessage() string {
	return v.Message
}

// SegmentStreamLaunchBackfillResponse is returned by SegmentStreamLaunchBackfill on success.
type SegmentStreamLaunchBackfillResponse struct {
	LaunchPartitionBackfill SegmentStreamLaunchBackfillLaunchPartitionBackfillLaunchBackfillResult `json:"-"`
}

// GetLaunchPartitionBackfill returns SegmentStreamLaunchBackfillResponse.LaunchPartitionBackfill, and is useful for accessing the field via an interface.
func (v *SegmentStreamLaunchBackfillResponse) GetLaunchPartitionBackfill() SegmentStreamLaunchBackfillLaunchPartitionBackfillLaunchBackfillResult {
	return v.LaunchPartitionBackfill
}

func (v *SegmentStreamLaunchBackfillResponse) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*SegmentStreamLaunchBackfillResponse
		LaunchPartitionBackfill json.RawMessage `json:"launchPartitionBackfill"`
		graphql.NoUnmarshalJSON
	}
	firstPass.SegmentStreamLaunchBackfillResponse = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.LaunchPartitionBackfill
		src := firstPass.LaunchPartitionBackfill
		if len(src) != 0 && string(src) != "null" {
			err = __unmarshalSegmentStreamLaunchBackfillLaunchPartitionBackfillLaunchBackfillResult(
				src, dst)
			if err != nil {
				return fmt.Errorf(
					"unable to unmarshal SegmentStreamLaunchBackfillResponse.LaunchPartitionBackfill: %w", err)
			}
		}
	}
	return nil
}

type __premarshalSegmentStreamLaunchBackfillResponse struct {
	LaunchPartitionBackfill json.RawMessage `json:"launchPartitionBackfill"`
}

func (v *SegmentStreamLaunchBackfillResponse) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *SegmentStreamLaunchBackfillResponse) __premarshalJSON() (*__premarshalSegmentStreamLaunchBackfillResponse, error) {
	var retval __premarshalSegmentStreamLaunchBackfillResponse

	{

		dst := &retval.LaunchPartitionBackfill
		src := v.LaunchPartitionBackfill
		var err error
		*dst, err = __marshalSegmentStreamLaunchBackfillLaunchPartitionBackfillLaunchBackfillResult(
			&src)
		if err != nil {
			return nil, fmt.Errorf(
				"unable to marshal SegmentStreamLaunchBackfillResponse.LaunchPartitionBackfill: %w", err)
		}
	}
	return &retval, nil
}

// SegmentStreamReadyResponse is returned by SegmentStreamReady on success.
type SegmentStreamReadyResponse struct {
	Version string `json:"version"`
}

// GetVersion returns SegmentStreamReadyResponse.Version, and is useful for accessing the field via an interface.
func (v *SegmentStreamReadyResponse) GetVersion() string { return v.Version }

// __SegmentStreamBackfillStatusInput is used internally by genqlient
type __SegmentStreamBackfillStatusInput struct {
	BackfillID string `json:"backfillID"`
}

// GetBackfillID returns __SegmentStreamBackfillStatusInput.BackfillID, and is useful for accessing the field via an interface.
func (v *__SegmentStreamBackfillStatusInput) GetBackfillID() string { return v.BackfillID }

// __SegmentStreamLaunchBackfillInput is used internally by genqlient
type __SegmentStreamLaunchBackfillInput struct {
	BackfillParams LaunchBackfillParams `json:"backfillParams"`
}

// GetBackfillParams returns __SegmentStreamLaunchBackfillInput.BackfillParams, and is useful for accessing the field via an interface.
func (v *__SegmentStreamLaunchBackfillInput) GetBackfillParams() LaunchBackfillParams {
	return v.BackfillParams
}

// The query executed by SegmentStreamAssets.
const SegmentStreamAssets_Operation = `
query SegmentStreamAssets {
	assetNodes {
		assetKey {
			path
		}
		isMaterializable
		isPartitioned
	}
}
`

func SegmentStreamAssets(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *SegmentStreamAssetsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "SegmentStreamAssets",
		Query:  SegmentStreamAssets_Operation,
	}

	data_ = &SegmentStreamAssetsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by SegmentStreamBackfillStatus.
const SegmentStreamBackfillStatus_Operation = `
query SegmentStreamBackfillStatus ($backfillID: String!) {
	partitionBackfillOrError(backfillId: $backfillID) {
		__typename
		... on PartitionBackfill {
			status
			error {
				message
			}
		}
		... on Error {
			message
		}
	}
}
`

func SegmentStreamBackfillStatus(
	ctx_ context.Context,
	client_ graphql.Client,
	backfillID string,
) (data_ *SegmentStreamBackfillStatusResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "SegmentStreamBackfillStatus",
		Query:  SegmentStreamBackfillStatus_Operation,
		Variables: &__SegmentStreamBackfillStatusInput{
			BackfillID: backfillID,
		},
	}

	data_ = &SegmentStreamBackfillStatusResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by SegmentStreamLaunchBackfill.
const SegmentStreamLaunchBackfill_Operation = `
mutation SegmentStreamLaunchBackfill ($backfillParams: LaunchBackfillParams!) {
	launchPartitionBackfill(backfillParams: $backfillParams) {
		__typename
		... on LaunchBackfillSuccess {
			backfillId
		}
		... on Error {
			message
		}
	}
}
`

func SegmentStreamLaunchBackfill(
	ctx_ context.Context,
	client_ graphql.Client,
	backfillParams LaunchBackfillParams,
) (data_ *SegmentStreamLaunchBackfillResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "SegmentStreamLaunchBackfill",
		Query:  SegmentStreamLaunchBackfill_Operation,
		Variables: &__SegmentStreamLaunchBackfillInput{
			BackfillParams: backfillParams,
		},
	}

	data_ = &SegmentStreamLaunchBackfillResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by SegmentStreamReady.
const SegmentStreamReady_Operation = `
query SegmentStreamReady {
	version
}
`

func SegmentStreamReady(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *SegmentStreamReadyResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "SegmentStreamReady",
		Query:  SegmentStreamReady_Operation,
	}

	data_ = &SegmentStreamReadyResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
