name: segmentstream_analytics_core
version: "0.1.0"
config-version: 2

profile: segmentstream

model-paths:
  - models
test-paths:
  - tests
macro-paths:
  - macros
seed-paths:
  - seeds
snapshot-paths:
  - snapshots

target-path: target
packages-install-path: dbt_packages
clean-targets:
  - target
  - dbt_packages

models:
  segmentstream_analytics_core:
    intermediate:
      conversion_events:
        +materialized: ephemeral
      events:
        +materialized: ephemeral
      identity:
        +materialized: ephemeral
    marts:
      +materialized: incremental
      +incremental_strategy: insert_overwrite
      events:
        +partition_by:
          field: event_date
          data_type: date
          granularity: day
      conversion_events:
        +partition_by:
          field: date
          data_type: date
          granularity: day
      identity_keys:
        +partition_by:
          field: date
          data_type: date
          granularity: day
      identity_links:
        +materialized: table
        +cluster_by:
          - source_anonymous_id
          - target_anonymous_id
      identities:
        +materialized: table
        +cluster_by:
          - identity_id
          - anonymous_id
